# Generated by Django 4.0.8 on 2022-10-11 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coffee', '0002_review'),
    ]

    operations = [
        migrations.AddField(
            model_name='coffee',
            name='front_picture',
            field=models.ImageField(blank=True, upload_to='front_picture/'),
        ),
    ]
