# Generated by Django 4.0.8 on 2022-10-12 14:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coffee', '0003_coffee_front_picture'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='coffee',
            options={'permissions': [('special_status', 'Can acceess all types of coffee')]},
        ),
    ]
