# Generated by Django 4.0.8 on 2022-10-12 14:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coffee', '0004_alter_coffee_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='coffee',
            options={'permissions': [('special_status', 'Can access all types of coffee')]},
        ),
    ]
