# Generated by Django 4.0.8 on 2022-10-12 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coffee', '0005_alter_coffee_options'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='coffee',
            index=models.Index(fields=['id'], name='id_index'),
        ),
    ]
